// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvisoryCondition } from "./AdvisoryCondition";
import type { AdvisoryLevel } from "./AdvisoryLevel";

export type Advisory = { id: string, 
/**
 * The name of the advisory, shown in the advisory list UI.
 * Does not appear in notices or when applying the advisory to a user.
 */
name: string, level: AdvisoryLevel, 
/**
 * The message template for this advisory, used to generate notices and when applying
 * the advisory to a user.
 * String substitution may be applied by the matching condition(s).
 */
message_template: string, 
/**
 * The conditions under which this advisory applies to a user.
 * To apply multiple conditions, use [AdvisoryCondition::AllOf] or [AdvisoryCondition::AnyOf].
 */
condition: AdvisoryCondition, 
/**
 * Custom tags to filter the advisory in the advisory list UI.
 */
tags: Array<string>, active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, 
/**
 * Whether to send a notification via XSOverlay, OVR Toolkit, or 
 * desktop notifications when this advisory matches.
 * Every matching and active advisory will generate a notice in History
 * and show an icon in the user list (if it's a user advisory), 
 * regardless of this setting.
 */
send_notification: boolean, 
/**
 * Whether to speak the advisory message via TTS when this advisory matches.
 */
send_tts: boolean, };
