// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conditions applied to a VRChat Group for an advisory. This way, a set of conditions can be applied to the same group, rather than to any group the user is in.
 */
export type AdvisoryGroupCondition = { "type": "Id", "data": string } | { "type": "NameContains", "data": string } | { "type": "OwnerIs", "data": string } | { "type": "Not", "data": { data: AdvisoryGroupCondition, } } | { "type": "AnyOf", "data": Array<AdvisoryGroupCondition> } | { "type": "AllOf", "data": Array<AdvisoryGroupCondition> } | { "type": "None" };
