// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvisoryLevel } from "./AdvisoryLevel";

export type Notice = { 
/**
 * The title of the notice. Usually "username joined" or "username changed avatars".
 */
title: string | null, message: string, level: AdvisoryLevel, relevantGroupId: string | null, relevantAdvisoryId: string | null, relevantUserId: string | null, 
/**
 * If this notice is only visible on the local machine.
 * This shows in the UI that "Only you can see this."
 */
local: boolean, sendTts: boolean, sendNotification: boolean, 
/**
 * Timestamp of when the notice was created, in RFC 3339 format.
 */
createdAt: string | null, };
