use serde::{Deserialize, Serialize};
use serde_repr::*;

#[derive(Debug, Clone, PartialEq, Eq, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum AdvisoryLevel {
    /// If this is the highest level of advisory for a user, the user list
    /// will sort them as if they have no advisories.
    None = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    /// Maximum-level advisories take effect immediately. TTS notifications
    /// for maximum-level advisories will cut off all others. Use this for
    /// members of known crasher groups.
    Maximum = 4,
}

/// An advisory applied to a user in the instance.
/// Advisories in storage or configuration use a type with the [VrcMrdAdvisory] trait.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActiveAdvisory {
    /// The advisory ID. Usually an ID generated by VRCMRD. This advisory ID may appear on multiple users, but
    /// only once for each user.
    /// The message, or message template, and other settings are the same for all advisories with the same ID.
    pub id: String,
    /// The advisory level of this advisory. A user with a higher-level advisory
    /// will be sorted higher in the user list.
    pub level: AdvisoryLevel,
    /// A message describing the advisory, i.e. names the relevant group and recommended action.
    pub message: String,
    /// The group ID relevant to this advisory, if any. This allows the group to be linked to
    /// in the UI.
    pub relevant_group_id: Option<String>,
}